ALTER TABLE AP_DIJANA.FLEX_STATUS
ADD (test_column VARCHAR2(10 Byte));


SET DEFINE OFF;
Insert into AP_DIJANA.FLEX_STATUS
   (SF_STATUS, STATUS_DESCRIPTION)
 Values
   ('1', 'test status');
Insert into AP_DIJANA.FLEX_STATUS
   (SF_STATUS, STATUS_DESCRIPTION, TEST_COLUMN)
 Values
   ('2', 'a', '55');
Insert into AP_DIJANA.FLEX_STATUS
   (SF_STATUS, STATUS_DESCRIPTION, TEST_COLUMN)
 Values
   ('3', 'b', '44');
Insert into AP_DIJANA.FLEX_STATUS
   (SF_STATUS, STATUS_DESCRIPTION, TEST_COLUMN)
 Values
   ('4', 'c', '33');
Insert into AP_DIJANA.FLEX_STATUS
   (SF_STATUS, STATUS_DESCRIPTION, TEST_COLUMN)
 Values
   ('5', 'd', '22');
Insert into AP_DIJANA.FLEX_STATUS
   (SF_STATUS, STATUS_DESCRIPTION, TEST_COLUMN)
 Values
   ('6', 'e', '11');
COMMIT;
